#!/bin/bash

# Create local-volume directories
for i in {1..10}
do
  mkdir -p /var/local/kubevirt-storage/local-volume/disk${i}
  mkdir -p /mnt/local-storage/local/disk${i}
done
chmod -R 777 /var/local/kubevirt-storage/local-volume

mknod /dev/loop0 b 7 0